name: moja_aplikacja
description: Opis aplikacji
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
